---
title: "Startup Mad-Libs"
type: "exercise"  # challenge, exercise, article, video
description: "Write your elevator pitch for your Space Exploration Program."
tags: "javascript, strings"
ignore:
- "startup-mad-libs.md"
